export default {
  tools: {
    react: 'React',
    node: 'Node',
    next: 'Next.js',
    native: 'React-native',
    gatsby: 'Gatsby',
    graphql: 'Graphql',
    realm: 'Realm',
    mysql: 'Mysql',
    postgres: 'PostgreSQL',
    javascript: 'Javascript',
    sass: 'Sass',
    html5: 'HTML5',
    dotnet: '.NET',
    sql: 'SQL',
    git: 'Git',
    csharp: 'C#',
    linq: 'Linq',
    aws: 'AWS',
    pwa: 'PWA',
    heroku: 'Heroku',
    jquery: 'jQuery',
    vanilla: 'Vanilla.js',
  },
};
